---
version: '3.2'
services:
  database:
    command: -c 'ssl=on' -c 'ssl_cert_file=/etc/pki/tls/certs/servercert.pem' -c 'ssl_key_file=/etc/pki/tls/private/serverkey.pem' -c 'ssl_ca_file=/etc/pki/CA/cacert.pem'
    container_name: postgresql
    environment:
      POSTGRES_PASSWORD: ${DATABASE_ROOT_PASSWORD}
    # ↓ @see https://devcenter.heroku.com/articles/heroku-postgresql#version-support-and-legacy-infrastructure
    image: postgres:10
    ports:
      - target: 5432
        published: 5432
    restart: always
    volumes:
      - /opt/datastore/postgresql:/var/lib/postgresql/data
      - ./mysql_conf.d:/etc/mysql/conf.d
      - /etc/pki:/etc/pki

  cache:
    container_name: redis
    image: redis:4
    ports:
      - target: 6379
        published: 6379
    restart: always

  web:
    container_name: web
    entrypoint:
      - sh
      - -cl
      - "cd /root && ansible-playbook ansistrano-symfony3-heroku/deploy_without_ansistrano.yml -i ansistrano-symfony3-heroku/inventories/development -vvv --extra-vars '{\"is_container\": true, \"symfony_env\": \"${SYMFONY_ENV}\", \"application_database_url\": \"postgres://postgres:${DATABASE_USER_PASSWORD}@database:5432/postgres?sslmode=require\", \"symfony_secret\": \"${SYMFONY_SECRET}\"}' && cd /app && heroku local -p 80"
    environment:
      SYMFONY_DATABASE_HOST: database
      SYMFONY_DATABASE_PASSWORD: ${DATABASE_USER_PASSWORD}
      SYMFONY_MYSQL_CA: ${SYMFONY_MYSQL_CA}
      SYMFONY_DATABASE_URL: postgres://postgres:${DATABASE_USER_PASSWORD}@database:5432/postgres?sslmode=require
      SYMFONY_LOG_LEVEL: ${SYMFONY_LOG_LEVEL}
      SYMFONY_REDIS_DSN_DEFAULT: redis://cache/0
      SYMFONY_REDIS_DSN_CACHE: redis://cache/1
      SYMFONY_REDIS_DSN_SESSION: redis://cache/2
      SYMFONY_REDIS_DSN_STORAGE: redis://cache/3
      SYMFONY_SECRET: ${SYMFONY_SECRET}
      SYMFONY_ENV: ${SYMFONY_ENV?err}
    image: futureys/heroku-php-apache2
    links:
      - database
      - cache
    ports:
      - 80:80
      - 8080:8080
    privileged: true
    # restart: always
    tty: true
    volumes:
#      - /etc/pki:/etc/pki
      - ./ansistrano-symfony3-heroku:/root/ansistrano-symfony3-heroku
      - ./symfony3-heroku:/app
      - /tmp/symfony3/var/cache:/app/var/cache
      - /tmp/symfony3/var/logs:/app/var/logs
      - /tmp/symfony3/var/sessions:/app/var/sessions
      - /tmp/symfony3/vendor:/app/vendor
