---
version: '3.2'
services:
  database:
    command: -c 'ssl=on' -c 'ssl_cert_file=/etc/pki/tls/certs/servercert.pem' -c 'ssl_key_file=/etc/pki/tls/private/serverkey.pem' -c 'ssl_ca_file=/etc/pki/CA/cacert.pem'
    container_name: postgresql
    environment:
      POSTGRES_PASSWORD: ${DATABASE_ROOT_PASSWORD}
    # ↓ @see https://devcenter.heroku.com/articles/heroku-postgresql#version-support-and-legacy-infrastructure
    image: postgres:10
    ports:
      - target: 5432
        published: 5432
    restart: always
    volumes:
      - /opt/datastore/postgresql:/var/lib/postgresql/data
      - ./mysql_conf.d:/etc/mysql/conf.d
      - /etc/pki:/etc/pki

  cache:
    container_name: redis
    image: redis:4
    ports:
      - target: 6379
        published: 6379
    restart: always

  web:
    container_name: web
    entrypoint:
      - sh
      - -cl
      - "cd /root && ansible-playbook ansistrano-wordpress-heroku/deploy_without_ansistrano.yml -i ansistrano-wordpress-heroku/inventories/development -vvv --extra-vars '{\"is_container\": true}' && cd /app && heroku local -p 80"
#      - /bin/bash
    environment:
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: ${DATABASE_USER_PASSWORD}
      # Optional variables
      DB_HOST: database
      # DB_PREFIX=wp_
      WP_ENV: ${WORDPRESS_ENV?err}
      WP_HOME: http://localhost
      WP_SITEURL: http://localhost/wp
      # Generate your keys here: https://roots.io/salts.html
      AUTH_KEY: ${WORDPRESS_AUTH_KEY}
      SECURE_AUTH_KEY: ${WORDPRESS_SECURE_AUTH_KEY}
      LOGGED_IN_KEY: ${WORDPRESS_LOGGED_IN_KEY}
      NONCE_KEY: ${WORDPRESS_NONCE_KEY}
      AUTH_SALT: ${WORDPRESS_AUTH_SALT}
      SECURE_AUTH_SALT: ${WORDPRESS_SECURE_AUTH_SALT}
      LOGGED_IN_SALT: ${WORDPRESS_LOGGED_IN_SALT}
      NONCE_SALT: ${WORDPRESS_NONCE_SALT}
#      SYMFONY_MYSQL_CA: ${SYMFONY_MYSQL_CA}
#      SYMFONY_DATABASE_URL: postgres://postgres:${DATABASE_USER_PASSWORD}@database:5432/postgres?sslmode=require
#      SYMFONY_LOG_LEVEL: ${SYMFONY_LOG_LEVEL}
#      SYMFONY_REDIS_DSN_DEFAULT: redis://cache/0
#      SYMFONY_REDIS_DSN_CACHE: redis://cache/1
#      SYMFONY_REDIS_DSN_SESSION: redis://cache/2
#      SYMFONY_REDIS_DSN_STORAGE: redis://cache/3
    image: futureys/heroku-php-apache2
    links:
      - database
      - cache
    ports:
      - 80:80
    privileged: true
    # restart: always
    tty: true
    volumes:
#      - /etc/pki:/etc/pki
      - ./ansistrano-wordpress-heroku:/root/ansistrano-wordpress-heroku
      - ./wordpress-heroku:/app
#      - /tmp/wordpress/var/cache:/app/var/cache
#      - /tmp/wordpress/var/logs:/app/var/logs
#      - /tmp/wordpress/var/sessions:/app/var/sessions
      - /tmp/wordpress/vendor:/app/vendor
